const ADMIN_BASE = '/manage-admin';
const ADMIN_AUTH_BASE = '/admin/auth';

const ADMIN_PATHS = {
  BASE: ADMIN_BASE,
  DASHBOARD: `${ADMIN_BASE}/dashboard`,
  ABOUT: `${ADMIN_BASE}/about`,
  ADMIN: {
    BASE: `${ADMIN_BASE}/admin`,
    LIST: `${ADMIN_BASE}/admin/adminList`,
    ROLES: `${ADMIN_BASE}/admin/roles`,
    SECURITY: `${ADMIN_BASE}/admin/security`,
    ACTIVITY: `${ADMIN_BASE}/admin/activity`,
    CREATE: `${ADMIN_BASE}/admin/create`,
  },
  SETTINGS: `${ADMIN_BASE}/settings`,
  PRODUCTS: {
    BASE: `${ADMIN_BASE}/products`,
    SOURCE: `${ADMIN_BASE}/products/source`,
    VIEWER: `${ADMIN_BASE}/products/productViewer`,
    EDITOR: `${ADMIN_BASE}/products/productEditor`,
    ADD: `${ADMIN_BASE}/products/addProduct`,
    ALIEXPRESS: `${ADMIN_BASE}/products/addProduct/aliexpress`,
    ALIEXPRESS_EDIT: `${ADMIN_BASE}/products/edit/aliexpress`,
    LIST: `${ADMIN_BASE}/products/productList`,
    EDIT: `${ADMIN_BASE}/products/editProduct/`,
    VIEW: `${ADMIN_BASE}/products/view/`,
    IMPORT: `${ADMIN_BASE}/products/import`,
  },
  ALIEXPRESS: `${ADMIN_BASE}/aliexpress`,
  ALIEXPRESS_INTEGRATION: `${ADMIN_BASE}/aliexpress-integration`,
  USERS: `${ADMIN_BASE}/users`,
  WORKUPDATE: `${ADMIN_BASE}/workUpdate`,
  B2C: `${ADMIN_BASE}/b2c`,
  D2C: `${ADMIN_BASE}/d2c`,
  PRICING: `${ADMIN_BASE}/pricing`,
  ORDERS: `${ADMIN_BASE}/orders`,
  ORDERS_PAGES: {
    ALL: `${ADMIN_BASE}/orders`,
    DETAILS: `${ADMIN_BASE}/orders/details`,
    MANUAL: `${ADMIN_BASE}/orders/manual`,
    ALIEXPRESS: `${ADMIN_BASE}/orders/aliexpress`,
    RECOVERY: `${ADMIN_BASE}/orders/recovery`,
    REFUNDS: `${ADMIN_BASE}/orders/refunds`,
    STATUS_LOGS: `${ADMIN_BASE}/orders/status-logs`,
  },
  SHIPPING: `${ADMIN_BASE}/shipping`,
  COURIER_INTEGRATION: `${ADMIN_BASE}/courier-integration`,
  CAMPAIGNS: `${ADMIN_BASE}/campaigns`,
  MARKETING: `${ADMIN_BASE}/marketing`,
  ANALYTICS: `${ADMIN_BASE}/analytics`,
  MEDIA: `${ADMIN_BASE}/media`,
  BACKUP: `${ADMIN_BASE}/backup`,
  DISPUTES: `${ADMIN_BASE}/disputes`,
  AUTH: {
    BASE: ADMIN_AUTH_BASE,
    LOGIN: `${ADMIN_AUTH_BASE}/login`,
    REGISTER: `${ADMIN_AUTH_BASE}/register`,
  },
};
export default ADMIN_PATHS